# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UMTF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='umtf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umtf.UMTF'),
        ),
    ]
