# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umtf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umtf', models.CharField(max_length=4, unique=True)),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
